### ISSUE TITLE
[Bug] Remove ERC721 Tokens

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Mask-Token-List#27]
+ ATRI 0xdacD69347dE42baBfAEcD09dC88958378780FB62
+ BCAP 0x1f41E42D0a9e3c0Dd3BA15B527342783B43200A9
+ CK 0x06012c8cf97BEaD5deAe237070F9587f8E7A266d
+ DCN 0x08d32b0da63e2C3bcF8019c9c5d849d7a9d791e6
+ EDG 0x08711D3B02C8758F2FB3ab4e80228418a7F8e39c
+ ROCK2 0xC16b542ff490e01fcc0DC58a60e1EFdc3e357cA6
+ KODA 0xFBeef911Dc5821886e1dda71586d90eD28174B7d
+ KDO 0x2aEa4Add166EBf38b63d09a75dE1a7b94Aa24163
+ MOD 0x957c30aB0426e0C93CD8241E2c60392d08c6aC8e
+ LAND 0x50f5474724e0Ee42D9a4e711ccFB275809Fd6d4a
+ SNGLS 0xaeC2E87E0A235266D9C5ADc9DEb4b2E29b54D009
+ SU 0xE9e3F9cfc1A64DFca53614a0182CFAD56c10624F

**Comment by lelenei** [comment]
https://erc721validator.org

 no ERC721:
ATRI 0xdacD69347dE42baBfAEcD09dC88958378780FB62
BCAP 0x1f41E42D0a9e3c0Dd3BA15B527342783B43200A9
 ERC165:
CK 0x06012c8cf97BEaD5deAe237070F9587f8E7A266d

**Comment by guanbinrui** [comment]
Below tokens, both satisfied EIP20 and EIP721.
